export type Row = {id:string; name:string; status:string; [key:string]:any};
export type Field = {key:string; label:string; type?:string; options?:string[]; required?:boolean};
const f=(key:string,label:string,type='text',options?:string[],required=false):Field=>({key,label,type,options,required});
const name=f('name','Name','text',undefined,true),status=(options:string[])=>f('status','Status','select',options,true);
export const roles=['owner','admin','support','content manager','seller manager'];
export const models:Record<string,{title:string; singular:string; description:string; fields:Field[]; columns:string[]}>={
 products:{title:'Products',singular:'product',description:'Every piece. Every variant. All in one place.',columns:['name','category','price','stock','sellerId','status'],fields:[name,f('description','Description','textarea'),f('image','Product image URL','url'),f('price','Price (₹)','number',undefined,true),f('stock','Available stock','number',undefined,true),f('variants','Sizes / variants (comma separated)'),f('category','Category','select',['T-shirts','Hoodies','Sweatshirts','Cargos','Jackets']),f('sellerId','Seller','seller',undefined,true),status(['active','draft','archived'])]},
 sellers:{title:'Sellers',singular:'seller',description:'Build your community. Keep your standards.',columns:['name','email','products','revenue','status'],fields:[name,f('email','Email','email',undefined,true),f('description','About the seller','textarea'),status(['pending','approved','rejected','suspended'])]},
 customers:{title:'Customers',singular:'customer',description:'Get to know the people behind every order.',columns:['name','email','orders','spent','status'],fields:[name,f('email','Email','email',undefined,true),f('notes','Private notes','textarea'),status(['active','blocked'])]},
 orders:{title:'Orders',singular:'order',description:'From checkout to their next favorite fit.',columns:['name','customer','total','payment','createdAt','status'],fields:[name,f('customer','Customer'),f('total','Order total (₹)','number'),f('tracking','Tracking reference'),f('notes','Fulfillment notes','textarea'),status(['processing','shipped','delivered','cancelled'])]},
 returns:{title:'Returns & refunds',singular:'return',description:'Track requests, inspections, and refund references.',columns:['name','orderId','total','reason','status'],fields:[name,f('orderId','Order ID','text',undefined,true),f('reason','Reason','textarea'),f('total','Refund amount (₹)','number'),f('reference','Payment provider refund reference'),status(['requested','approved','rejected','received','refund pending','refunded'])]},
 coupons:{title:'Coupons',singular:'coupon',description:'Give your next drop a little extra pull.',columns:['name','discountType','value','usageLimit','end','status'],fields:[f('name','Coupon code','text',undefined,true),f('discountType','Discount type','select',['percentage','fixed']),f('value','Discount value','number',undefined,true),f('start','Starts at','datetime-local'),f('end','Ends at','datetime-local'),f('usageLimit','Total usage limit','number'),f('minimum','Minimum order (₹)','number'),f('products','Eligible product IDs (comma separated)'),f('categories','Eligible categories (comma separated)'),f('sellers','Eligible seller IDs (comma separated)'),status(['active','paused'])]},
 announcements:{title:'Announcements',singular:'announcement',description:'The first thing your customers see. Make it count.',columns:['name','start','end','status'],fields:[f('name','Banner message','text',undefined,true),f('link','Link'),f('start','Starts at','datetime-local'),f('end','Ends at','datetime-local'),f('priority','Priority (higher appears first)','number'),status(['active','draft','paused'])]},
 tickets:{title:'Support inbox',singular:'ticket',description:'A little help goes a long way.',columns:['name','customer','audience','priority','status'],fields:[f('name','Subject','text',undefined,true),f('customer','Customer / seller email','email'),f('audience','From','select',['customer','seller']),f('priority','Priority','select',['normal','high','urgent']),f('body','Message','textarea'),f('reply','Reply / internal note','textarea'),status(['open','in progress','resolved'])]},
 pages:{title:'Pages & homepage',singular:'page',description:'Your story, your way. No code needed.',columns:['name','slug','placement','status'],fields:[f('name','Page title','text',undefined,true),f('slug','URL slug','text',undefined,true),f('placement','Placement','select',['page','homepage']),f('body','Page copy','textarea'),f('sections','Sections (one heading | body per line)','textarea'),f('position','Display order','number'),status(['draft','published'])]},
 navigation:{title:'Navigation',singular:'menu item',description:'Help shoppers find their next favorite.',columns:['name','link','position','status'],fields:[f('name','Menu label','text',undefined,true),f('link','Destination','text',undefined,true),f('position','Display order','number'),status(['published','draft'])]},
 promotions:{title:'Banners & promotions',singular:'promotion',description:'Put your next campaign in the spotlight.',columns:['name','start','end','status'],fields:[name,f('body','Supporting copy','textarea'),f('image','Banner image URL','url'),f('link','Destination'),f('start','Starts at','datetime-local'),f('end','Ends at','datetime-local'),status(['active','draft','paused'])]},
 users:{title:'Team & permissions',singular:'team member',description:'Give everyone the access they need.',columns:['name','email','role','status'],fields:[name,f('email','Email','email',undefined,true),f('role','Role','select',roles.slice(1)),status(['active','disabled'])]},
 notifications:{title:'Notifications',singular:'notification',description:'Your store’s latest updates.',columns:['name','createdAt','status'],fields:[name,status(['unread','read'])]},
 audit:{title:'Audit log',singular:'event',description:'A clear record of who changed what and when.',columns:['name','actor','target','createdAt'],fields:[]},
 settings:{title:'Store settings',singular:'setting',description:'The details that make Hypox yours.',columns:['name','value'],fields:[name,f('value','Value','textarea')]}
};
export const permissions:Record<string,string[]>={owner:['*'],admin:['*'],support:['dashboard','customers','orders','returns','tickets','notifications'], 'content manager':['dashboard','products','pages','announcements','navigation','promotions','notifications'], 'seller manager':['dashboard','sellers','products','tickets','notifications']};
export const can=(role:string,resource:string)=>!!permissions[role]?.some(x=>x==='*'||x===resource);
export const currency=(v:number)=>new Intl.NumberFormat('en-IN',{style:'currency',currency:'INR',maximumFractionDigits:0}).format(v||0);
