import {Row} from './crm-models';
const photo=(s:string)=>'/images/'+s+'.jpg';
export const seed:Record<string,Row[]>={
products:[['midnight-tee','Midnight oversized tee','T-shirts',899,42,'black-tee'],['afterhours-hoodie','Afterhours heavyweight hoodie','Hoodies',1999,8,'hoodie'],['utility-cargo','Utility relaxed cargos','Cargos',1799,23,'cargo'],['blank-canvas-tee','Blank canvas boxy tee','T-shirts',799,64,'white-tee'],['terrain-jacket','Terrain utility jacket','Jackets',2499,5,'jacket'],['off-duty-crew','Off-duty crewneck','Sweatshirts',1499,31,'sweatshirt']].map(p=>({id:String(p[0]),name:String(p[1]),category:p[2],price:p[3],stock:p[4],image:photo(String(p[5])),sellerId:'seller-1',variants:'S, M, L, XL, XXL',status:'active',description:'Everyday essentials. Made for your own kind of different.',createdAt:'2026-09-01'})),
sellers:[{id:'seller-1',name:'Hypox Studio',email:'studio@example.invalid',products:6,revenue:148260,status:'approved'},{id:'seller-2',name:'Afterhours Supply',email:'hello@example.invalid',products:0,revenue:0,status:'pending',description:'Independent streetwear label from Bengaluru.'},{id:'seller-3',name:'Off Grid Collective',email:'offgrid@example.invalid',products:0,revenue:0,status:'pending',description:'Small-batch essentials from Mumbai.'},{id:'seller-4',name:'No Signal',email:'nosignal@example.invalid',products:0,revenue:0,status:'suspended'}],
customers:['Aarav Sharma','Ananya Patel','Riya Mehta','Kabir Singh','Ishaan Rao','Zoya Khan','Neha Kapoor','Dev Shah','Mira Das','Aryan Bose','Tara Roy'].map((name,i)=>({id:'customer-'+i,name,email:name.toLowerCase().replace(' ','.')+'@example.invalid',orders:i+1,spent:899*(i+1),status:'active'})),
orders:Array.from({length:42},(_,i)=>({id:'order-'+i,name:'#HX-'+(2084-i),customer:['Aarav Sharma','Ananya Patel','Riya Mehta','Kabir Singh','Zoya Khan'][i%5],customerId:'customer-'+i%5,productId:['midnight-tee','afterhours-hoodie','utility-cargo'][i%3],sellerId:'seller-1',total:[2697,1999,3598,899,4298][i%5],payment:'paid',coupon:i%4===0?'FIRSTDROP':'',createdAt:new Date(Date.UTC(2026,8,25-(i%28),10,i)).toISOString(),status:['processing','shipped','delivered','delivered','delivered'][i%5]})),
coupons:[{id:'coupon-1',name:'FIRSTDROP',discountType:'percentage',value:15,minimum:1499,usageLimit:500,start:'2026-09-01T00:00',end:'2026-10-01T00:00',status:'active'},{id:'coupon-2',name:'FESTIVE200',discountType:'fixed',value:200,minimum:1999,usageLimit:250,start:'2026-10-01T00:00',end:'2026-11-15T23:59',status:'paused'}],
announcements:[{id:'announcement-1',name:'NEW SEASON. SAME ENERGY. Free shipping on orders ₹2,999+',start:'2026-09-01T00:00',end:'2026-10-31T23:59',priority:1,status:'active',link:'/shop'}],
tickets:[{id:'ticket-1',name:'Can I exchange my hoodie for a larger size?',customer:'riya.mehta@example.invalid',audience:'customer',priority:'high',body:'My hoodie arrived today. Could I exchange the M for an L?',status:'open'},{id:'ticket-2',name:'Help with my first product listing',customer:'hello@example.invalid',audience:'seller',priority:'normal',body:'I would like help adding my product images and sizes.',status:'open'},{id:'ticket-3',name:'Where is my order #HX-2079?',customer:'aarav.sharma@example.invalid',audience:'customer',priority:'urgent',body:'Could you share an update on shipping?',status:'in progress'}],
returns:[{id:'return-1',name:'Hoodie size exchange',orderId:'order-2',total:1999,reason:'Size too small',status:'requested'}],
pages:[{id:'page-1',name:'Our story',slug:'our-story',body:'For your own kind of different.',sections:'Made for you | Everyday pieces that feel like you.\nOur community | Independent labels. Shared energy.',placement:'page',position:1,status:'published'}],
navigation:[{id:'nav-1',name:'New arrivals',link:'/shop?sort=newest',position:1,status:'published'},{id:'nav-2',name:'Our story',link:'/pages/our-story',position:2,status:'published'}],
promotions:[{id:'promo-1',name:'The next chapter',body:'Fresh fits for the festive season.',link:'/shop',start:'2026-10-01T00:00',end:'2026-11-01T00:00',status:'draft'}],
users:[],settings:[{id:'store-name',name:'Store name',value:'Hypox Clothing',status:'active'},{id:'support-email',name:'Support email',value:'',status:'active'}],
notifications:[{id:'notice-1',name:'2 sellers are waiting for approval',createdAt:'2026-09-25T09:00:00Z',status:'unread'},{id:'notice-2',name:'Terrain utility jacket is running low',createdAt:'2026-09-25T08:00:00Z',status:'unread'}],audit:[]};

