import {db,all,first,HttpError,now,id,config} from './server';
import {models,can,Row,roles} from './crm-models';
import {seed} from './crm-sample';
export async function crmRole(actor:string){if(actor.toLowerCase()===config().CRM_OWNER_EMAIL?.toLowerCase())return 'owner';const member=await first("SELECT data FROM crm_records WHERE mode='live' AND resource='users' AND lower(json_extract(data,'$.email'))=? AND json_extract(data,'$.status')='active'",actor.toLowerCase());if(!member)throw new HttpError(403,'This account does not have admin access. Ask the owner to add you to the team.');return JSON.parse(member.data).role}
export async function records(mode:string,resource:string){return(await all('SELECT data FROM crm_records WHERE mode=? AND resource=? ORDER BY updatedAt DESC LIMIT 5000',mode,resource)).map(r=>JSON.parse(r.data))}
export function saveStatement(mode:string,resource:string,row:Row){return db().prepare('INSERT INTO crm_records (key,mode,resource,data,updatedAt) VALUES (?,?,?,?,?) ON CONFLICT(key) DO UPDATE SET data=excluded.data,updatedAt=excluded.updatedAt').bind(mode+':'+resource+':'+row.id,mode,resource,JSON.stringify(row),now())}
function auditStatement(actor:string,mode:string,action:string,target:string){const row={id:id(),name:action,actor,target,createdAt:now(),status:'recorded'};return saveStatement(mode,'audit',row)}
async function seedWorkspace(){if(await first("SELECT key FROM crm_records WHERE key='demo:initialized'"))return;await db().batch([db().prepare("INSERT OR IGNORE INTO crm_records (key,mode,resource,data,updatedAt) VALUES ('demo:initialized','demo','_meta','{}',?)").bind(now()),...Object.entries(seed).flatMap(([resource,rows])=>rows.map(row=>db().prepare('INSERT OR IGNORE INTO crm_records (key,mode,resource,data,updatedAt) VALUES (?,?,?,?,?)').bind('demo:'+resource+':'+row.id,'demo',resource,JSON.stringify(row),now())))])}
export async function liveRows(resource:string):Promise<Row[]>{
 const extra=await records('live',resource);const merge=(rows:any[])=>rows.map(r=>({...extra.find(x=>x.id===r.id),...r}));
 if(resource==='products')return merge((await all('SELECT * FROM products ORDER BY createdAt DESC LIMIT 5000')).map(p=>({...p,price:p.price/100,status:p.active?'active':extra.find(x=>x.id===p.id)?.status==='archived'?'archived':'draft',image:p.image,variants:extra.find(x=>x.id===p.id)?.variants||'S, M, L, XL, XXL'})));
 if(resource==='sellers')return merge((await all("SELECT u.id,u.name,u.email,u.role,a.id applicationId,a.storeName,a.description,a.status applicationStatus,(SELECT COUNT(*) FROM products WHERE sellerId=u.id) products FROM users u LEFT JOIN seller_applications a ON a.userId=u.id WHERE u.role='seller' OR a.id IS NOT NULL")).map(s=>({...s,name:s.storeName||s.name,status:s.applicationStatus||(s.role==='seller'?'approved':'pending')})));
 if(resource==='customers')return merge((await all("SELECT u.id,u.name,u.email,(SELECT COUNT(*) FROM orders WHERE userId=u.id) orders,(SELECT COALESCE(SUM(total),0)/100.0 FROM orders WHERE userId=u.id AND paymentStatus='paid') spent FROM users u WHERE role='customer' LIMIT 5000")).map(c=>({...c,status:extra.find(x=>x.id===c.id)?.status||'active'})));
 if(resource==='orders')return merge((await all('SELECT o.*,u.name customer,(SELECT productId FROM order_items WHERE orderId=o.id LIMIT 1) productId,(SELECT sellerId FROM order_items WHERE orderId=o.id LIMIT 1) sellerId FROM orders o JOIN users u ON o.userId=u.id ORDER BY o.createdAt DESC LIMIT 5000')).map(o=>({...o,name:'#'+o.id.slice(0,8).toUpperCase(),total:o.total/100,payment:o.paymentStatus,customerId:o.userId})));
 if(resource==='returns')return merge((await all('SELECT r.*,o.total FROM returns r JOIN orders o ON o.id=r.orderId ORDER BY r.createdAt DESC LIMIT 5000')).map(r=>({...r,name:'Return #'+r.id.slice(0,8),total:r.total/100,status:r.status.replaceAll('_',' ')})));
 if(resource==='coupons')return (await all('SELECT * FROM coupons')).map(c=>{const e=extra.find(x=>x.id===c.code);return {id:c.code,name:c.code,discountType:'percentage',value:c.percent,minimum:c.minimum/100,end:c.expiresAt.slice(0,16),...e,status:c.active?'active':'paused'}});
 if(resource==='tickets'){const messages=await all('SELECT m.*,u.email customer,u.role audience FROM messages m JOIN users u ON u.id=m.userId ORDER BY m.createdAt DESC LIMIT 5000');return [...messages.map(m=>({...m,name:m.subject,status:'open',priority:'normal',...extra.find(x=>x.id===m.id)})),...extra.filter(e=>!messages.some(m=>m.id===e.id))]}
 if(resource==='notifications'){const counts=[{id:'pending-sellers',name:(await first("SELECT COUNT(*) n FROM seller_applications WHERE status='pending'")).n+' seller applications to review'},{id:'low-stock',name:(await first('SELECT COUNT(*) n FROM products WHERE active=1 AND stock<10')).n+' products below 10 units'}];return counts.map(n=>({...n,status:'unread',createdAt:now(),...extra.find(e=>e.id===n.id),name:n.name}));}
 return extra;
}
export function validate(resource:string,input:any):Row{
 const model=models[resource];if(!model||!input||typeof input!=='object')throw new HttpError(400,'Invalid record');
 const row:Row={id:typeof input.id==='string'?input.id.slice(0,100):'',name:'',status:'active'};
 for(const field of model.fields){let value=input[field.key];if(field.required&&(value===undefined||value===null||String(value).trim()===''))throw new HttpError(400,field.label+' is required');if(field.type==='number'){value=Number(value||0);if(!Number.isFinite(value)||value<0||value>100000000)throw new HttpError(400,field.label+' must be a valid non-negative number');}else{value=String(value||'').trim();if(value.length>(field.type==='textarea'?8000:500))throw new HttpError(400,field.label+' is too long');}if(field.options&&!field.options.includes(value))throw new HttpError(400,'Choose a valid '+field.label);if(field.type==='email'&&value&&!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(value))throw new HttpError(400,'Enter a valid email');if(['link','image'].includes(field.key)&&value&&!(/^(https:\/\/|\/(?!\/))/.test(value)))throw new HttpError(400,'Use a secure HTTPS URL or a local /path');row[field.key]=value;}
 if(row.start&&row.end&&Date.parse(row.start)>=Date.parse(row.end))throw new HttpError(400,'End date must be after the start date');
 for(const k of ['start','end'])if(row[k]&&!Number.isFinite(Date.parse(row[k])))throw new HttpError(400,'Enter a valid date');
 if(resource==='products'&&(!Number.isInteger(row.stock)||row.price<=0))throw new HttpError(400,'Stock must be a whole number and price must be positive');
 if(resource==='coupons'){row.name=row.name.toUpperCase();if(!/^[A-Z0-9_-]{2,40}$/.test(row.name))throw new HttpError(400,'Use 2–40 letters, numbers, hyphens or underscores for coupon codes');if(row.value<=0||(row.discountType==='percentage'&&row.value>100))throw new HttpError(400,'Enter a valid discount');if(!Number.isInteger(row.usageLimit))throw new HttpError(400,'Usage limit must be a whole number');}
 if(resource==='pages'&&!/^[a-z0-9]+(?:-[a-z0-9]+)*$/.test(row.slug))throw new HttpError(400,'Use a lowercase page slug with hyphens');
 if(resource==='returns'&&row.status==='refunded'&&!row.reference)throw new HttpError(400,'A payment provider refund reference is required');
 return row;
}
async function liveStatements(resource:string,row:Row,old?:Row){const q=db();const statements:D1PreparedStatement[]=[];
 if(resource==='products'){const seller=await first("SELECT id FROM users WHERE id=? AND role='seller'",row.sellerId);if(!seller)throw new HttpError(400,'Assign an approved seller');statements.push(q.prepare('INSERT INTO products (id,sellerId,name,brand,category,description,price,stock,image,active,createdAt) VALUES (?,?,?,?,?,?,?,?,?,?,?) ON CONFLICT(id) DO UPDATE SET sellerId=excluded.sellerId,name=excluded.name,category=excluded.category,description=excluded.description,price=excluded.price,stock=excluded.stock,image=excluded.image,active=excluded.active').bind(row.id,row.sellerId,row.name,'Hypox',row.category||'T-shirts',row.description||'',Math.round(row.price*100),row.stock,(row.image||'').replace('https://hypox-clothing.shamipos.chatgpt.site',''),row.status==='active'?1:0,now()));}
 if(resource==='sellers'){if(!old)throw new HttpError(400,'Sellers must apply through the storefront');statements.push(q.prepare("UPDATE users SET role=? WHERE id=? AND role IN ('customer','seller')").bind(row.status==='approved'?'seller':'customer',row.id));if(old.applicationId)statements.push(q.prepare('UPDATE seller_applications SET status=?,storeName=?,description=? WHERE userId=?').bind(row.status,row.name,row.description,row.id));else statements.push(q.prepare('INSERT INTO seller_applications (id,userId,storeName,description,status,createdAt) VALUES (?,?,?,?,?,?)').bind(id(),row.id,row.name,row.description||'',row.status,now()));if(row.status!=='approved')statements.push(q.prepare('UPDATE products SET active=0 WHERE sellerId=?').bind(row.id));}
 if(resource==='customers'){if(!old)throw new HttpError(400,'Customers are created through store sign-in');statements.push(q.prepare('UPDATE users SET name=? WHERE id=?').bind(row.name,row.id));if(row.status==='blocked')statements.push(q.prepare('DELETE FROM sessions WHERE userId=?').bind(row.id));}
 if(resource==='orders'){if(!old)throw new HttpError(400,'Orders must originate at checkout');if(row.status!==old.status){const allowed:Record<string,string[]>= {processing:['shipped'],shipped:['delivered']};if(!allowed[old.status]?.includes(row.status))throw new HttpError(400,'Only processing → shipped → delivered can be updated here. Use the payment provider for cancellations.');if(!['paid','simulated'].includes(old.payment))throw new HttpError(400,'Only paid or simulated orders can be fulfilled');}statements.push(q.prepare('UPDATE orders SET status=?,tracking=?,deliveredAt=CASE WHEN ?=\'delivered\' THEN COALESCE(deliveredAt,?) ELSE deliveredAt END WHERE id=? AND status=?').bind(row.status,row.tracking||'',row.status,now(),row.id,old.status));row.total=old.total;row.customer=old.customer;}
 if(resource==='returns'){if(!old)throw new HttpError(400,'Return requests must originate from a delivered order');statements.push(q.prepare('UPDATE returns SET status=? WHERE id=?').bind(row.status.replaceAll(' ','_'),row.id));row.orderId=old.orderId;row.total=old.total;}
 if(resource==='coupons'){if(old&&row.name!==old.name)throw new HttpError(400,'Coupon codes cannot be renamed. Create a new coupon.');row.id=row.name;statements.push(q.prepare('INSERT INTO coupons (code,percent,minimum,maximum,active,expiresAt) VALUES (?,?,?,?,?,?) ON CONFLICT(code) DO UPDATE SET percent=excluded.percent,minimum=excluded.minimum,active=excluded.active,expiresAt=excluded.expiresAt').bind(row.name,row.discountType==='percentage'?row.value:0,Math.round((row.minimum||0)*100),100000000,row.status==='active'?1:0,row.end?new Date(row.end).toISOString():'2099-12-31T23:59:59.000Z'));}
 if(resource==='tickets'&&row.reply&&row.reply!==old?.reply){const u=await first('SELECT id FROM users WHERE email=?',row.customer);if(u)statements.push(q.prepare('INSERT INTO notifications (id,userId,message,createdAt) VALUES (?,?,?,?)').bind(id(),u.id,row.name+': '+row.reply,now()));}
 return statements;
}
export async function handleCrm(input:any){const actor=String(input.actor||'').toLowerCase();const role=await crmRole(actor);const mode=input.mode==='live'?'live':'demo';if(mode==='demo')await seedWorkspace();
 if(input.action==='load'){const data:Record<string,Row[]>={};for(const resource of Object.keys(models)){if(!can(role,resource)||(resource==='users'&&role!=='owner')){data[resource]=[];continue}data[resource]=mode==='demo'?await records(mode,resource):await liveRows(resource);}if(can(role,'orders'))data.orderLines=mode==='demo'?(data.orders||[]).map(o=>({id:o.id,name:o.name,status:o.status,orderId:o.id,productId:o.productId,sellerId:o.sellerId,total:o.total,createdAt:o.createdAt,payment:o.payment})):await all("SELECT i.id,i.name,i.orderId,i.productId,i.sellerId,i.price*i.quantity/100.0 total,o.createdAt,o.paymentStatus payment,o.status FROM order_items i JOIN orders o ON o.id=i.orderId ORDER BY o.createdAt DESC LIMIT 10000");return {data,role,name:input.name||actor}}
 const resource=String(input.resource||'');if(!models[resource]||!can(role,resource)||resource==='audit'||(resource==='users'&&role!=='owner'))throw new HttpError(403,'Your role cannot make this change');
 const existing=mode==='demo'?await records(mode,resource):await liveRows(resource);const statements:D1PreparedStatement[]=[];
 if(input.action==='save'){const row=validate(resource,input.row);const old=existing.find(r=>r.id===row.id);if(row.id&&!old)throw new HttpError(404,'Record no longer exists');row.id=row.id||id();row.createdAt=old?.createdAt||now();if(resource==='users'){if(row.email.toLowerCase()===config().CRM_OWNER_EMAIL?.toLowerCase())throw new HttpError(400,'Owner access cannot be changed');if(existing.some(r=>r.id!==row.id&&r.email?.toLowerCase()===row.email.toLowerCase()))throw new HttpError(409,'This team member already exists');}
 if(resource==='coupons'&&existing.some(r=>r.id!==row.id&&r.name===row.name))throw new HttpError(409,'Coupon code already exists');
 if(resource==='pages'&&existing.some(r=>r.id!==row.id&&r.slug===row.slug))throw new HttpError(409,'Page slug already exists');
 if(resource==='products'){const sellers=mode==='demo'?await records(mode,'sellers'):await liveRows('sellers');if(!sellers.some(s=>s.id===row.sellerId&&s.status==='approved'))throw new HttpError(400,'Choose an approved seller');}
 if(mode==='live')statements.push(...await liveStatements(resource,row,old));
 statements.push(saveStatement(mode,resource,{...old,...row}),auditStatement(actor,mode,'Saved '+resource,row.name));
 }else if(input.action==='delete'||input.action==='bulk'){const ids=input.ids;if(!Array.isArray(ids)||!ids.length||ids.length>100||ids.some(v=>typeof v!=='string'))throw new HttpError(400,'Select between 1 and 100 records');
 if(input.action==='delete'&&!['products','coupons','announcements','pages','navigation','promotions'].includes(resource))throw new HttpError(403,'These records cannot be deleted');
 for(const key of ids){const old=existing.find(r=>r.id===key);if(!old)throw new HttpError(404,'Record no longer exists');if(input.action==='bulk'){if(!['sellers','notifications'].includes(resource))throw new HttpError(400,'Bulk action unavailable');const row=validate(resource,{...old,status:input.status});if(mode==='live')statements.push(...await liveStatements(resource,row,old));statements.push(saveStatement(mode,resource,{...old,...row}));}else{if(mode==='live'&&resource==='products')statements.push(db().prepare('UPDATE products SET active=0 WHERE id=?').bind(key));else if(mode==='live'&&resource==='coupons')statements.push(db().prepare('UPDATE coupons SET active=0 WHERE code=?').bind(key));if(mode==='live'&&['products','coupons'].includes(resource))statements.push(saveStatement(mode,resource,{...old,status:resource==='products'?'archived':'paused'}));else statements.push(db().prepare('DELETE FROM crm_records WHERE key=?').bind(mode+':'+resource+':'+key));}statements.push(auditStatement(actor,mode,input.action+' '+resource,old.name));}
 }else throw new HttpError(400,'Unknown action');
 if(statements.length)await db().batch(statements);return{ok:true};
}





