import type { Product } from "./types";
const rows = [
  [
    "midnight-tee",
    "Midnight oversized tee",
    "T-shirts",
    89900,
    119900,
    "black-tee",
    "CORE ESSENTIAL",
  ],
  [
    "afterhours-hoodie",
    "Afterhours heavyweight hoodie",
    "Hoodies",
    199900,
    249900,
    "hoodie",
    "THE FIRST DROP",
  ],
  [
    "utility-cargo",
    "Utility relaxed cargos",
    "Cargos",
    179900,
    219900,
    "cargo",
    "STREET UNIFORM",
  ],
  [
    "blank-canvas-tee",
    "Blank canvas boxy tee",
    "T-shirts",
    79900,
    99900,
    "white-tee",
    "EVERYDAY ROTATION",
  ],
  [
    "terrain-jacket",
    "Terrain utility jacket",
    "Jackets",
    249900,
    299900,
    "jacket",
    "LAYER UP",
  ],
  [
    "off-duty-crew",
    "Off-duty crewneck",
    "Sweatshirts",
    149900,
    189900,
    "sweatshirt",
    "OFF THE CLOCK",
  ],
  [
    "shadow-tee",
    "Shadow essential tee",
    "T-shirts",
    99900,
    129900,
    "black-tee",
    "NEW ARRIVAL",
  ],
  [
    "nightfall-hoodie",
    "Nightfall relaxed hoodie",
    "Hoodies",
    219900,
    269900,
    "hoodie",
    "RELAXED FIT",
  ],
  [
    "concrete-cargo",
    "Concrete straight cargos",
    "Cargos",
    189900,
    229900,
    "cargo",
    "MOVE YOUR WAY",
  ],
  [
    "daily-white-tee",
    "Daily white relaxed tee",
    "T-shirts",
    69900,
    89900,
    "white-tee",
    "LESS, BUT BETTER",
  ],
  [
    "urban-shell",
    "Urban utility layer",
    "Jackets",
    279900,
    329900,
    "jacket",
    "CITY READY",
  ],
  [
    "weekend-crew",
    "Weekend oversized crew",
    "Sweatshirts",
    169900,
    209900,
    "sweatshirt",
    "COMFORT ZONE",
  ],
] as const;
export const sampleProducts: Product[] = rows.map((r, i) => ({
  id: r[0],
  name: r[1],
  category: r[2],
  brand: "HypoX",
  price: r[3],
  comparePrice: r[4],
  image: "/images/" + r[5] + ".jpg",
  badge: r[6],
  stock: 20 + i,
  description:
    "Your everyday rotation, with your own point of view. A relaxed streetwear silhouette made to wear your way. Sample collection: photos are illustrative; final fabric composition, garment measurements, and care labels will be confirmed before live sales. Sizes S–XXL. Available stock is pooled across sizes in this starter.",
  rating: 0,
  reviewCount: 0,
  sellerId: "hypox-studio",
  active: 1,
  createdAt: new Date(Date.UTC(2026, 8, 25, 0, i)).toISOString(),
}));
